### ISSUE TITLE
Wordpress = Bad

### ISSUE THREAD

**Issue by joshvickerson** [sergeychernyshev/.htaccess#15]
Right now, this doesn't work with Wordpress sites. I added it to my blog and was happy to see my Google Page Speed score raise by 8 points (a noticeable improvement) but it broke all links to my posts (404's), homepage loaded fine.

Wordpress requires the following for mod_rewrite, apparently: 

<IfModule mod_rewrite.c>
ErrorDocument 404 /index.php?error=404
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

Should we fork this for a Wordpress-friendly file? Or is there a better solution I'm missing? I would like to use this for my site but I'm unsure of the best way of going about making it work.

**Comment by sergeychernyshev** [comment]
I don't think we can possibly accommodate all frameworks and applications with this file, it's probably better to use appropriate plugins that know WordPress specifics.
